version: "3.8"

services:
  master:
    image: alokranjan2000/ansible_nodes
    networks:
      - ansible_net
    volumes:
      - ./ansible:/etc/ansible
      - sshkey:/public_key
    command: >
      bash -c "
      ssh-keygen -t ed25519 -f /home/ansible/.ssh/id_rsa -N '' -C 'docker-ansible-key' &&
      chown ansible:ansible /home/ansible/.ssh/id_rsa /home/ansible/.ssh/id_rsa.pub &&
      cp /home/ansible/.ssh/id_rsa.pub /public_key/id_rsa.pub &&
      /usr/sbin/sshd -D
      "
    deploy:
      placement:
        constraints: [node.role == manager]

  target:
    image: alokranjan2000/ansible_nodes
    networks:
      - ansible_net
    ports:
      - "8080:8080"
    volumes:
      - sshkey:/tmp/sshkey_ro:ro
    command: >
      bash -c "
      mkdir -p /home/ansible/.ssh &&
      cat /tmp/sshkey_ro/id_rsa.pub >> /home/ansible/.ssh/authorized_keys &&
      chown ansible:ansible /home/ansible/.ssh &&
      chmod 700 /home/ansible/.ssh &&
      chown root:root /home/ansible/.ssh/authorized_keys &&
      chmod 604 /home/ansible/.ssh/authorized_keys &&
      /usr/sbin/sshd -D
      "
    deploy:
      replicas: 4

volumes:
  sshkey:

networks:
  ansible_net:
    driver: overlay
